### ISSUE TITLE
can't install pcl

### ISSUE THREAD

**Issue by xuzhang5788** [Durant35/VoxNet#4]
Thank you for your work.

For installing your library, you mentioned "$Root". Is it the real root or directory name of your library? After git clone your library, there is a Voxnet directory created. Based on your instruction of installing your library, I think your root is Voxnet directory. 

I met difficulties to install pcl. When I run $python setup.py build_ext -i, I got:
setup.py: error: cannot find PCL, tried
    pkg-config pcl_common-1.8
    pkg-config pcl_common-1.7
    pkg-config pcl_common-1.6
    pkg-config pcl_common

I got similar errors when I run  $python setup.py install.

Any advice? Thanks a lot.

**Comment by Durant35** [comment]
Maybe you can try：https://github.com/Durant35/python-pcl/wiki
